name: Build Red Vision Firmware

on:
  pull_request:
  push:
    branches:
      - v1.26.0-preview-beta2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build Firmware
      run: source tools/build_red_vision.sh && build_micropython_red_vision
